#!/usr/bin/env node
/**
 * Filecoin Onchain Cloud (FOC) Integration Demo
 *
 * Demonstrates the full agent workflow:
 * 1. Buyer posts a task on ServiceBoard (Base Sepolia)
 * 2. Seller discovers and claims the task
 * 3. Seller executes task → stores result on Filecoin Onchain Cloud
 * 4. Seller submits PieceCID as delivery hash on-chain
 * 5. Buyer retrieves content from FOC → verifies → confirms delivery
 * 6. Escrow released, reputation updated
 *
 * Runs in simulation mode without FILECOIN_PRIVATE_KEY.
 * Set FILECOIN_PRIVATE_KEY for real FOC storage on calibration testnet.
 *
 * Usage:
 *   node agents/src/filecoin/demo.js              # simulation mode
 *   FILECOIN_PRIVATE_KEY=0x... node agents/src/filecoin/demo.js  # real FOC
 *
 * @module filecoin/demo
 */

import { config } from 'dotenv';
config({ path: '../.env' });

import { AgentStorage } from './client.js';

// ═══════════════════════════════════════════════════════════════════
// Demo: Standalone Filecoin storage (no on-chain escrow needed)
// ═══════════════════════════════════════════════════════════════════

async function runStandaloneDemo() {
  console.log('╔══════════════════════════════════════════════════════════════╗');
  console.log('║  🗄️  Filecoin Onchain Cloud — AgentEscrow Integration Demo  ║');
  console.log('╚══════════════════════════════════════════════════════════════╝');
  console.log();

  const filecoinKey = process.env.FILECOIN_PRIVATE_KEY;
  const network = process.env.FILECOIN_NETWORK || 'calibration';

  const storage = new AgentStorage({ privateKey: filecoinKey, network });

  // ── Step 1: Store a task delivery ──────────────────────────────
  console.log('━━━ Step 1: Store Task Delivery on Filecoin ━━━');
  const delivery1 = await storage.storeDelivery({
    taskId: 42,
    taskType: 'text_summary',
    result: 'Summary: The AgentEscrow protocol enables autonomous AI agents to trade services using smart contract escrow. Key points: (1) Trustless agent-to-agent commerce via EscrowVault, (2) Reputation tracking via ReputationRegistry, (3) Task discovery via ServiceBoard. The protocol supports text summaries, code reviews, translations, and name generation. [Generated by AgentEscrow Seller Agent]',
    agentAddress: '0xC07b695eC19DE38f1e62e825585B2818077B96cC',
    agentERC8004Id: '2195',
  });
  console.log(`   Receipt: ${JSON.stringify(delivery1, null, 2)}`);
  console.log();

  // ── Step 2: Store a code review delivery ───────────────────────
  console.log('━━━ Step 2: Store Code Review Delivery ━━━');
  const delivery2 = await storage.storeDelivery({
    taskId: 43,
    taskType: 'code_review',
    result: 'Code Review Report:\n- Structure: Well-organized Solidity contracts following OpenZeppelin patterns\n- Security: No reentrancy vulnerabilities detected; uses checks-effects-interactions\n- Gas: Consider using calldata instead of memory for read-only params\n- Testing: 8/8 tests passing, good coverage of edge cases\n- Rating: 8/10\n[Generated by AgentEscrow Seller Agent]',
    agentAddress: '0xC07b695eC19DE38f1e62e825585B2818077B96cC',
    agentERC8004Id: '2195',
  });
  console.log(`   Receipt: ${JSON.stringify(delivery2, null, 2)}`);
  console.log();

  // ── Step 3: Store agent memory ─────────────────────────────────
  console.log('━━━ Step 3: Store Agent Memory on Filecoin ━━━');
  const memoryReceipt = await storage.storeData({
    type: 'agent_memory',
    content: {
      agentId: '2195',
      session: 'demo-session-001',
      tasksCompleted: [42, 43],
      totalEarned: '0.002 ETH',
      trustScore: 100,
      capabilities: ['text_summary', 'code_review', 'name_generation', 'translation'],
      lastActive: new Date().toISOString(),
    },
    metadata: {
      protocol: 'agentescrow',
      chain: 'base-sepolia',
      erc8004Registry: '0x8004A818BFB912233c491871b3d84c89A494BD9e',
    },
  });
  console.log(`   Receipt: ${JSON.stringify(memoryReceipt, null, 2)}`);
  console.log();

  // ── Step 4: Store Venice TEE attestation ───────────────────────
  console.log('━━━ Step 4: Store TEE Attestation on Filecoin ━━━');
  const attestationReceipt = await storage.storeData({
    type: 'tee_attestation',
    content: {
      model: 'tee-deepseek-r1-671b',
      taskId: 42,
      enclaveId: 'sgx-venice-prod-001',
      attestationHash: '0x' + 'a1b2c3d4'.repeat(8),
      verified: true,
      timestamp: new Date().toISOString(),
    },
    metadata: {
      provider: 'venice.ai',
      privacyLevel: 'TEE',
      encryptionType: 'hardware-isolation',
    },
  });
  console.log(`   Receipt: ${JSON.stringify(attestationReceipt, null, 2)}`);
  console.log();

  // ── Step 5: Retrieve and verify ────────────────────────────────
  console.log('━━━ Step 5: Retrieve & Verify from Filecoin ━━━');
  console.log('Buyer retrieving task #42 delivery...');
  const retrieved = await storage.retrieve(delivery1.pieceCid);
  console.log(`   ✅ Retrieved content:`);
  console.log(`   Task ID: ${retrieved.taskId}`);
  console.log(`   Type: ${retrieved.taskType}`);
  console.log(`   Result: ${retrieved.result.substring(0, 100)}...`);
  console.log(`   Agent: ${retrieved.agent.address}`);
  console.log(`   ERC-8004: ${retrieved.agent.erc8004Id}`);
  console.log(`   Stored: ${retrieved.timestamp}`);
  console.log();

  // ── Step 6: Cost estimate ──────────────────────────────────────
  console.log('━━━ Step 6: Storage Cost Estimate ━━━');
  const cost = await storage.estimateCost(1024 * 1024); // 1 MB
  console.log(`   ${JSON.stringify(cost, null, 2)}`);
  console.log();

  // ── Summary ────────────────────────────────────────────────────
  console.log('╔══════════════════════════════════════════════════════════════╗');
  console.log('║                      📊 Demo Summary                       ║');
  console.log('╠══════════════════════════════════════════════════════════════╣');
  console.log(`║  Deliveries stored:    2 (task_summary + code_review)       ║`);
  console.log(`║  Agent memory stored:  1 session snapshot                   ║`);
  console.log(`║  TEE attestations:     1 Venice attestation                 ║`);
  console.log(`║  Total items on FOC:   4                                    ║`);
  console.log(`║  Retrieval verified:   ✅ Content matches                   ║`);
  console.log(`║  Network:              ${(storage.network + (storage.simulation ? ' (sim)' : '')).padEnd(37)}║`);
  console.log('╠══════════════════════════════════════════════════════════════╣');
  console.log('║                                                              ║');
  console.log('║  Use Case: Autonomous Agent Task Marketplace                ║');
  console.log('║  • Agents store task results on Filecoin (immutable)        ║');
  console.log('║  • PieceCID serves as verifiable delivery hash              ║');
  console.log('║  • Buyers retrieve & verify before confirming escrow        ║');
  console.log('║  • TEE attestations archived for audit trail                ║');
  console.log('║  • Agent memory persists across sessions                    ║');
  console.log('║                                                              ║');
  console.log('╚══════════════════════════════════════════════════════════════╝');

  return {
    deliveries: [delivery1, delivery2],
    memory: memoryReceipt,
    attestation: attestationReceipt,
  };
}

runStandaloneDemo().catch(err => {
  console.error('Demo failed:', err);
  process.exit(1);
});
